### PR TITLE
Add helper to create a consumer key

### PR DESCRIPTION
**Pull request by gregdel**

### CODE REVIEW

**Comment by yadutaf** [comment]
Looks good ! Thanks. Can you sign your commit and remove the "feat" prefix as you suggested ? I'll squash + sign all my commits when migrating to github.com/ovh.

**Comment by gregdel** [comment]
I removed the "feat" prefix. I've also signed my commit :)

**Comment by yadutaf** [comment]
The signature appears to be missing :(

**Comment by gregdel** [comment]
The commit was signed, but I can't figure out how to view this on github.
I've added a "signoff" to this commit, is that what you want ?

**Comment by gregdel** [comment]
I may have misunderstood your request, should I signoff my commits and sign them with my gpg key, or should I only signoff ?

**Comment by yadutaf** [comment]
Yup :) Merged. Thanks.

**Pull request merged**
